project:
  type: website
  output-dir: docs

website:
  title: "Erin Franke"
  navbar:
    background: '#FFFFFF'
    left:
      - href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research" 
      - href: teaching.qmd
        text: "Teaching"
      - href: posts.qmd
        text: "Posts" 
      - text: Other
        menu: 
          - href: tidytuesday.qmd
            text: "Tidy Tuesday"
          - href: projects.qmd
            text: "Undergrad"
    tools:
      - icon: file-person
        text: CV
        href: docs/cv.pdf
  page-footer: 
    left: |
      &copy; Erin Franke, 2025 <br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

